version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '[%(asctime)s] %(levelname)7s | %(name)s | %(module)s | %(message)s'
    dateformat: '%Y-%m-%d %H:%M'

handlers:
  error_console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr

  console:
    class: logging.StreamHandler
    level: ${LOG_LEVEL_APP_CONSOLE:-DEBUG}
    formatter: simple
    stream: ext://sys.stdout

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ${LOG_DIR}/errors.log
    maxBytes: 10485760
    backupCount: 3

  app_file:
    class: logging.handlers.RotatingFileHandler
    level: ${LOG_LEVEL_FILE:-INFO}
    formatter: simple
    filename: ${LOG_DIR}/app.log
    maxBytes: 52428800
    backupCount: 5

  app_presentation_file:
    class: logging.handlers.RotatingFileHandler
    level: ${LOG_LEVEL_FILE:-INFO}
    formatter: simple
    filename: ${LOG_DIR}/app_presentation.log
    maxBytes: 52428800
    backupCount: 5

  app_business_file:
    class: logging.handlers.RotatingFileHandler
    level: ${LOG_LEVEL_FILE:-INFO}
    formatter: simple
    filename: ${LOG_DIR}/app_business.log
    maxBytes: 52428800
    backupCount: 5

  app_data_file:
    class: logging.handlers.RotatingFileHandler
    level: ${LOG_LEVEL_FILE:-INFO}
    formatter: simple
    filename: ${LOG_DIR}/app_data.log
    maxBytes: 52428800
    backupCount: 5

loggers:
  app:
    level: ${LOG_LEVEL_LOGGERS:-DEBUG}
    handlers:
      - console
      - app_file
    propagate: true

  app.presentation:
    level: ${LOG_LEVEL_LOGGERS:-DEBUG}
    handlers:
      - app_presentation_file
    propagate: true

  app.business:
    level: ${LOG_LEVEL_LOGGERS:-DEBUG}
    handlers:
      - app_business_file
    propagate: true

  app.data:
    level: ${LOG_LEVEL_LOGGERS:-DEBUG}
    handlers:
      - app_data_file
    propagate: true

root:
  level: ERROR
  handlers:
    - error_console
    - error_file